package chatclient;

import FrameChucNang.About;
import FrameChucNang.ChangePass;
import FrameChucNang.ChosseColor;
import FrameChucNang.Review;
import FrameChucNang.ToPrivateClient;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.Buffer;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.ListModel;

/**
 *
 * @author AnhThu
 */
public class MClient extends javax.swing.JFrame {

    private DataInputStream din;
    private DataOutputStream dos;
    private String User;
    private static Hashtable mHashtable;
    private String StNgonNgu = "None";
    private ChosseColor FrCl;
    private int typestr = 0;
    private String fontname;
    private int Size = 14;
    private StringBuilder strReview;
    private SystemTrayTest trayMclient;

    public String getUser() {
        return User;
    }

    static {
        mHashtable = new Hashtable();
    }

    /**
     * Creates new form MClient
     */
    public void set(DataInputStream din, DataOutputStream dos, String User) {
        this.din = din;
        this.dos = dos;
        this.User = User;
        txtUserName.setText(User);
        setTitle(User);
    }

    public JTextArea getTxtMain() {
        return txtMain;
    }

    public void AddUser(String user, ToPrivateClient mToClient) {
        mHashtable.put(user, mToClient);
    }

    public static void RemoveUser(String user) {
        mHashtable.remove(user);
    }

    public void Receive() {
        InClient mInClient = new InClient(din);
        Thread mThread = new Thread(mInClient);
        mThread.start();
    }


    public MClient() {

        initComponents();
        setAlwaysOnTop(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("img/iconClientx.png")));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((dim.width - getWidth()) / 2, (dim.height - getHeight()) / 2, getWidth(), getHeight());
        //load font cho combobox
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font font[] = ge.getAllFonts();
        for (int i = 0; i < font.length; i++) {
            cbfont.addItem(font[i].getFontName());
        }
        cbfont.setSelectedIndex(49);
        strReview=new StringBuilder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMain = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        txtUserName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JListUser = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIn = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        cbfont = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        B = new javax.swing.JButton();
        I = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFocusTraversalPolicyProvider(true);

        txtMain.setEditable(false);
        txtMain.setColumns(20);
        txtMain.setLineWrap(true);
        txtMain.setRows(5);
        txtMain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(246, 202, 17), null), "Multilingual Messenger!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 3, 12), new java.awt.Color(204, 0, 153))); // NOI18N
        txtMain.setMaximumSize(null);
        jScrollPane1.setViewportView(txtMain);

        btnSend.setBackground(new java.awt.Color(0, 204, 255));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/img/btSend.png"))); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 0, 204));

        JListUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List User Online", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 2, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        JListUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListUserMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(JListUser);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/img/lbLogo.gif"))); // NOI18N
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204)));
        txtIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtIn);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/img/lbChat.png"))); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Arabic", "Bulgarian", "Catalan", "Chinese_simplified", "Chinese_traditional", "Czech", "Danish", "Dutch", "English", "Estonian", "Finnish", "French", "German", "Greek", "Haitian_creole", "Hebrew", "Hindi", "Hmong_daw", "Hungarian", "Indonesian", "Italian", "Japanese", "Korean", "Latvian", "Lithuanian", "Malay", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Slovak", "Slovenian", "Spanish", "Swedish", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/img/selectlg.gif"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 204), new java.awt.Color(255, 255, 51), null, null));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatclient/img/chosecolor.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setEditable(true);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "8", "12", "14", "16", "18", "20", "24", "28", "32", "36", "38", "40", "44", "48", "52", "58", "60", "68", "72" }));
        jComboBox2.setSelectedIndex(3);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        cbfont.setEditable(true);
        cbfont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfontActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Font");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setText("Size");

        B.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        I.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Review");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("ChangePassword");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Sign Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Function");

        jMenuItem5.setText("History");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSend))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(cbfont, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(I)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2))
                        .addGap(43, 43, 43)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(I, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(cbfont, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
      // TODO add your handling code here:
      try {
          String str = txtIn.getText().trim();
          if (!str.equals("")) {
              String str2 = "2," + User + "," + str;
              dos.writeUTF(str2);
              txtMain.append(User + ":  " + str + "\n");
              txtIn.setText("");
              strReview.append(User).append( ":  ").append( str).append("\n");
          }
      } catch (Exception e) {
          //err
      }
  }//GEN-LAST:event_btnSendActionPerformed

  private void txtInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInKeyPressed
      // TODO add your handling code here:
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          btnSendActionPerformed(null);
      }
  }//GEN-LAST:event_txtInKeyPressed

  private void JListUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListUserMouseClicked
      // TODO add your handling code here:
      try {
          if (evt.getClickCount() == 2) {
              int index = JListUser.locationToIndex(evt.getPoint());
              ListModel dlm = JListUser.getModel();
              String item = (String) dlm.getElementAt(index);
              JListUser.ensureIndexIsVisible(index);
              ToPrivateClient mToClient = new ToPrivateClient();
              mToClient.setDos(dos);
              mToClient.setUser(User);
              mToClient.setUserReceive(item);
              AddUser(item, mToClient);
              mToClient.setVisible(true);
              //System.out.println("Double clicked on " + item);
          }
      } catch (IndexOutOfBoundsException e) {
      }
  }//GEN-LAST:event_JListUserMouseClicked

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      this.dispose();
  }//GEN-LAST:event_formWindowClosing

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        StNgonNgu = (String) cb.getSelectedItem();
        System.out.println(StNgonNgu);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ChangePass(this).setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrCl = new ChosseColor(this);
        FrCl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbfontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfontActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();
        fontname = (String) cb.getSelectedItem();
        txtMain.setFont(new Font(fontname, typestr, Size));
        int a = cb.getSelectedIndex();
        System.out.println(a);
    }//GEN-LAST:event_cbfontActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        JComboBox cbb = (JComboBox) evt.getSource();
        String strsize = (String) cbb.getSelectedItem();
        Size = Integer.parseInt(strsize);
        txtMain.setFont(new Font(fontname, typestr, Size));
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        if (typestr == 0 || typestr == 2) {
            typestr++;
            B.setForeground(Color.red);
        } else if (typestr == 1 || typestr == 3) {
            typestr--;
            B.setForeground(Color.BLACK);
        }
        txtMain.setFont(new Font(fontname, typestr, Size));
    }//GEN-LAST:event_BActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        if (typestr == 0) {
            typestr = 2;
            I.setForeground(Color.red);
        } else if (typestr == 1) {
            typestr += 2;
            I.setForeground(Color.red);
        } else if (typestr == 2) {
            typestr = 0;
            I.setForeground(Color.BLACK);
        } else if (typestr == 3) {
            typestr -= 2;
            I.setForeground(Color.BLACK);
        }
        txtMain.setFont(new Font(fontname, typestr, Size));
    }//GEN-LAST:event_IActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int jp = JOptionPane.showConfirmDialog(null, "Are You Sign Out?", "Exit", JOptionPane.YES_NO_OPTION);
        if (jp == JOptionPane.YES_OPTION) {
            try {
                dos.writeUTF("111,true"); //logout
//                dos.writeUTF("1,a,c");
                this.dispose();
                trayMclient.removeStray();
                new Login().setVisible(true);

            } catch (IOException ex) {
                Logger.getLogger(MClient.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int jp = JOptionPane.showConfirmDialog(null, "Are You Exit Programer", "Exit", JOptionPane.YES_NO_OPTION);
        if (jp == JOptionPane.YES_OPTION) {
            try {
                dos.writeUTF("111,true"); //logout
                dos.writeUTF("1,a,c");
                System.exit(0);
            } catch (IOException ex) {
                Logger.getLogger(MClient.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Review(strReview).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton I;
    private javax.swing.JList JListUser;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox cbfont;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane txtIn;
    private javax.swing.JTextArea txtMain;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables

    void setTray(SystemTrayTest MclientTray) {
        trayMclient = MclientTray;

    }

    class InClient implements Runnable {

        private DataInputStream din;

        public InClient(DataInputStream din) {
            this.din = din;
        }

        @Override
        public void run() {
            Read();
        }

        public void Read() {
            String[] temp = null;
            try {
                while (true) {
                    String in = din.readUTF();
                    if (!in.isEmpty()) {
                        temp = in.split(",");
                        // xu ly khi nhan duoc du lieu
                        if ("0".equals(temp[0])) {
                            //setList Account
                            String[] tmp = new String[temp.length - 1];
                            for (int i = 1; i < temp.length; i++) {
                                //if (!tmp[i].equals(User)) {
                                tmp[i - 1] = temp[i];
                                //}
                            }
                            //set List account cho Client;
                            JListUser.setListData(tmp);
                        } else if ("22".equals(temp[0])) {
                            //client to client -find user object
                            if (!ShowOneClient(temp[2], temp[1])) {
                                ToPrivateClient mToClient = new ToPrivateClient();
                                mToClient.setDos(dos);
                                mToClient.setUser(User);
                                mToClient.setUserReceive(temp[1]);
                                AddUser(temp[1], mToClient);
                                mToClient.setVisible(true);
                                mToClient.ShowMsg(temp[2], temp[1]);
                                try {
                                    Thread.sleep(300);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(MClient.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        } else if ("2".equals(temp[0])) {
                            try {
                                if (!temp[1].equals(User)) {
                                    String dich = TranslateST(temp[2]);
                                    txtMain.append(temp[1] + ":  " + dich + "\n");
                                    strReview.append(temp[1]).append(":  ").append(temp[2]).append("\n");
                                    txtMain.setCaretPosition(txtMain.getDocument().getLength());
                                }

                            } catch (Exception e) {
                                System.out.println("loi");
                            }
                        } else {
                            //Lenh sai
                        }
                    }
                }
            } catch (ArrayIndexOutOfBoundsException | IOException e) {
                JOptionPane.showConfirmDialog(null, "Server tạm ngưng hoạt động", "ERROR SERVER",
                        JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
                formWindowClosing(null);
            }
        }

        private boolean ShowOneClient(String msg, String UserSend) {
            Enumeration e = mHashtable.keys();
            ToPrivateClient mToClient;
            System.out.println(msg);
            while (e.hasMoreElements()) {
                //mdos.close();
                String key = (String) (e.nextElement());
                if (key.equals(UserSend)) {
                    mToClient = (ToPrivateClient) mHashtable.get(key);
                    mToClient.ShowMsg(msg, UserSend);
                    return true;
                }
            }
            return false;
        }
    }

    public String TranslateST(String st) {
        MTranslate dich = new MTranslate();
        String strdich = dich.TranslateST(st, StNgonNgu);
        return strdich;
    }
}
